version: '3'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    ports:
      - '8080:80'
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - '9000:9000'
    links:
      - db:mongodb
  db:
    image: mongo:3.6.2
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
