# Build environment
FROM node:8.11.1-alpine as builder
WORKDIR /app
COPY . .
RUN yarn install
ENV NODE_ENV production
RUN yarn build

# Production environment
FROM nginx:1.13.1-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
